<?php
	Flight::map('getCurrency', function($currencyCode) {
		switch ($currencyCode) {
			case 'USD':
				return '$';
			case 'EUR':
				return '€';
			case 'JPY':
				return '¥';
			case 'GBP':
				return '£';
			case 'AUD':
				return 'A$';
			case 'CAD':
				return 'C$';
			case 'CHF':
				return 'CHF';
			case 'CNY':
				return 'CN¥';
			case 'SEK':
				return 'kr';
			case 'NZD':
				return 'NZ$';
			case 'MXN':
				return 'Mex$';
			case 'SGD':
				return 'S$';
			case 'HKD':
				return 'HK$';
			case 'NOK':
				return 'kr';
			case 'KRW':
				return '₩';
			case 'TRY':
				return '₺';
			case 'INR':
				return '₹';
			case 'RUB':
				return '₽';
			case 'BRL':
				return 'R$';
			case 'ZAR':
				return 'R';
			case 'DKK':
				return 'kr';
			case 'PLN':
				return 'zł';
			case 'THB':
				return '฿';
			case 'IDR':
				return 'Rp';
			case 'HUF':
				return 'Ft';
			case 'MYR':
				return 'RM';
			case 'RON':
				return 'lei';
			case 'ARS':
				return 'ARS$';
			case 'CZK':
				return 'Kč';
			case 'CLP':
				return 'CLP$';
			case 'COP':
				return 'COL$';
			case 'PHP':
				return '₱';
			case 'ILS':
				return '₪';
			case 'AED':
				return 'AED';
			case 'KWD':
				return 'KD';
			case 'QAR':
				return 'QR';
			case 'SAR':
				return 'SR';
			case 'SGD':
				return 'S$';
			case 'TWD':
				return 'NT$';
			case 'UAE':
				return 'AED';
			case 'ZMW':
				return 'ZK';
			default:
					return ''; // Domyślna wartość, gdy nie ma dopasowania
		}
	});